Repository qurbat/upi-recon, pull requests merged in 2022-05, with the labels that each got.

#3 Introduce support for Google Pay addresses
  .gitignore
  README.md
  config/config.ini
  config/config.ini.example
  upi-recon.py
Labels: enhancement

#7 Add VPA suffixes as a file
  upi-recon.py
  vpa_suffixes.txt
Labels: enhancement

#11 Add new query types, disclaimer information, and minor performance-related changes
  README.md
  data/fastag_suffixes.txt
  data/general_suffixes.txt
  data/gpay_suffixes.txt
  upi-recon.py
Labels: documentation, enhancement, pending review

#17 Update README.md to clarify requirement of live API credentials
  README.md
Labels: documentation, pending review

#14 Proposed changes to README
  README.md
Labels: documentation, in progress

#19 Update more suffixes
  .gitpod.yml
  README.md
  data/general_suffixes.txt
  data/mobile_suffixes.txt
  upi-recon.py
Labels: documentation, enhancement

#26 Enhancements and hotfix
  upi-recon.py
Labels: bug, enhancement
